export const mockStoragePoolGuid = 'default';
export const storagePoolsData = {
    [mockStoragePoolGuid]: {
        id: 1,
        GUID: 'default',
        TenantGUID: 'default',
        EncryptionKeyGUID: 'a9d47c1f-08f6-4fc8-bd91-6b3e3c908a9e',
        Name: 'Primary Storage Pool',
        Provider: 'AWS',
        WriteMode: 'GUID',
        UseSsl: true,
        Endpoint: 'https://s3.amazonaws.com',
        AccessKey: 'AKIAEXAMPLEKEY',
        SecretKey: 'SECRETEXAMPLEKEY',
        AwsRegion: 'us-west-1',
        AwsBucket: 'my-app-bucket',
        AwsBaseDomain: 'https://s3.amazonaws.com',
        AwsBaseUrl: 'https://my-app-bucket.s3.amazonaws.com',
        DiskDirectory: null,
        AzureAccount: null,
        AzureContainer: null,
        Compress: 'NONE',
        EnableReadCaching: true,
        CreatedUtc: '2024-09-24T10:15:30Z'
    },
    a7sd89as7d7s8979da79da8: {
        id: 2,
        GUID: 'a7sd89as7d7s8979da79da8',
        TenantGUID: 'default',
        EncryptionKeyGUID: 'a9d47c1f-08f6-4fc8-bd91-6b3e3c908a9e',
        Name: 'Primary Storage Pool',
        Provider: 'AWS',
        WriteMode: 'GUID',
        UseSsl: true,
        Endpoint: 'https://s3.amazonaws.com',
        AccessKey: 'AKIAEXAMPLEKEY',
        SecretKey: 'SECRETEXAMPLEKEY',
        AwsRegion: 'us-west-1',
        AwsBucket: 'my-app-bucket',
        AwsBaseDomain: 'https://s3.amazonaws.com',
        AwsBaseUrl: 'https://my-app-bucket.s3.amazonaws.com',
        DiskDirectory: null,
        AzureAccount: null,
        AzureContainer: null,
        Compress: 'NONE',
        EnableReadCaching: true,
        CreatedUtc: '2024-09-24T10:15:30Z'
    },
};
export const storagePoolsMockApiResponse = Object.values(storagePoolsData);
